### Register
POST http://127.0.0.1:8000/register
Content-Type: application/json

{
    "email": "gregedmonds17@gmail.com",
    "first_name": "G",
    "last_name": "E",
    "password": "greg1234"
}

### Login
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    "email": "gregedmonds17@gmail.com",
    "password": "greg1234"
}

### Reset password
POST http://127.0.0.1:8000/password_reset/ HTTP/1.1
Content-Type: application/json

{
    "email": "gregedmonds17@gmail.com"
}
### Confirm reset password
POST http://127.0.0.1:8000/password_reset/confirm/ HTTP/1.1
Content-Type: application/json

{
    "token": "a9bd7b31e8e051e6260079cb23506d2dcae3881c9142",
    "password": "newpassword44"
}

### Get users
GET http://127.0.0.1:8000/users HTTP/1.1
Content-Type: application/json
Authorization: Token 9e5930486cadc4a664eae6d5b7d5b6805947b508