# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LabShare-Front' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LabShare-Front

  target 'LabShare-FrontTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LabShare-FrontUITests' do
    # Pods for testing
  end

end
