# Generated by Django 3.1 on 2020-10-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(blank=True, default=''),
        ),
    ]
