# Generated by Django 3.1 on 2020-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_name',
            field=models.TextField(default='image1'),
        ),
    ]
