# Generated by Django 3.1 on 2020-09-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LabShare.post'),
        ),
    ]
