# Generated by Django 3.1 on 2020-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0004_auto_20201001_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profile_image'),
        ),
    ]
