# Generated by Django 3.1 on 2020-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0005_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
