# Generated by Django 3.1.1 on 2020-10-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0004_merge_20200929_1814'),
        ('LabShare', '0004_merge_20200929_1634'),
        ('LabShare', '0005_userprofile_image'),
    ]

    operations = [
    ]
