# Generated by Django 3.1.1 on 2020-10-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0006_merge_20201002_1048'),
        ('LabShare', '0006_auto_20201004_1556'),
    ]

    operations = [
    ]
