# Generated by Django 3.1.1 on 2020-10-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0007_merge_20201004_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
