# Generated by Django 3.1 on 2020-09-17 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0008_auto_20200917_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categoryName',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 17, 8, 1, 25, 980670), null=True),
        ),
    ]
