# Generated by Django 3.1 on 2020-09-17 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0009_auto_20200917_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 17, 10, 2, 47, 388075), null=True),
        ),
    ]
