# Generated by Django 3.1 on 2020-09-18 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0012_auto_20200917_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 18, 15, 9, 38, 320836), null=True),
        ),
    ]
