# Generated by Django 3.1.1 on 2020-09-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0011_auto_20200913_1843'),
        ('LabShare', '0017_auto_20200918_1613'),
    ]

    operations = [
    ]
