# Generated by Django 3.1.1 on 2020-09-19 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0018_merge_20200919_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 19, 17, 28, 30, 813880), null=True),
        ),
    ]
