# Generated by Django 3.1.1 on 2020-09-19 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0019_auto_20200919_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 19, 19, 14, 48, 996862), null=True),
        ),
    ]
