# Generated by Django 3.1.1 on 2020-09-20 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0020_auto_20200919_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 20, 7, 27, 2, 341270), null=True),
        ),
    ]
