# Generated by Django 3.1.1 on 2020-09-21 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0021_auto_20200920_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 21, 11, 10, 41, 473590), null=True),
        ),
    ]
