# Generated by Django 3.1.1 on 2020-09-20 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0021_auto_20200920_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 20, 16, 2, 38, 480572), null=True),
        ),
    ]
