# Generated by Django 3.1.1 on 2020-09-20 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0023_auto_20200920_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 20, 16, 20, 57, 339815)),
        ),
    ]
