# Generated by Django 3.1.1 on 2020-09-22 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0022_auto_20200921_1110'),
        ('LabShare', '0024_auto_20200920_1620'),
    ]

    operations = [
    ]
