# Generated by Django 3.1.1 on 2020-09-22 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabShare', '0025_merge_20200922_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 22, 14, 19, 40, 607441)),
        ),
    ]
