# Generated by Django 3.1 on 2020-09-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_auto_20200828_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorName',
            field=models.TextField(default='none'),
        ),
    ]
