# Generated by Django 3.1 on 2020-09-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_post_authorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authorName',
        ),
    ]
