# Generated by Django 3.1 on 2020-08-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-date_posted']},
        ),
    ]
